# Generated by Django 5.2.12 on 2026-03-11 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                ("abstract", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("morphology", "Morphology"),
                            ("genomics", "Genomics"),
                            ("histology", "Histology"),
                            ("ct_mri", "CT / MRI"),
                            ("behavioural", "Behavioural"),
                        ],
                        default="morphology",
                        max_length=50,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("cc_by_4", "CC BY 4.0"),
                            ("cc_by_nc_4", "CC BY-NC 4.0"),
                            ("cc0", "CC0"),
                            ("restricted", "Restricted"),
                        ],
                        default="cc_by_4",
                        max_length=20,
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(default="v1", max_length=20)),
                ("species", models.CharField(blank=True, max_length=200)),
                ("specimen_count", models.PositiveIntegerField(blank=True, null=True)),
                ("collection_date", models.DateField(blank=True, null=True)),
                ("anatomical_region", models.CharField(blank=True, max_length=200)),
                ("lab", models.CharField(blank=True, max_length=200)),
                ("institution", models.CharField(blank=True, max_length=200)),
                (
                    "file_size_display",
                    models.CharField(
                        blank=True, help_text="e.g. 14.2 MB", max_length=50
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="datasets", to="repository.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="datasets/files/")),
                ("filename", models.CharField(max_length=300)),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="repository.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="datasets/notebooks/"
                    ),
                ),
                ("filename", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("colab_url", models.URLField(blank=True)),
                ("binder_url", models.URLField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to="repository.dataset",
                    ),
                ),
            ],
        ),
    ]
