# Generated by Django 5.2.12 on 2026-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="category",
            field=models.CharField(
                choices=[
                    ("flame", "Flame"),
                    ("mechanical", "Mechanical"),
                    ("chemical", "Chemical"),
                    ("imaging", "Imaging"),
                ],
                default="flame",
                max_length=50,
            ),
        ),
    ]
