# Generated by Django 5.2.12 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0003_add_sample_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notebook",
            options={"ordering": ["uploaded_at"]},
        ),
        migrations.AddField(
            model_name="notebook",
            name="code",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="tab_label",
            field=models.CharField(default="Notebook", max_length=100),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="filename",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
