# Generated by Django 5.2.12 on 2026-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0006_samplecolumn_unit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="samplevalue",
            index=models.Index(
                fields=["column", "value"], name="samplevalue_col_val_idx"
            ),
        ),
    ]
