# Generated by Django 5.2.12 on 2026-03-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0011_add_dashboard_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="entry_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notebook",
            name="extracted_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notebook",
            name="zip_file",
            field=models.FileField(
                blank=True, null=True, upload_to="datasets/dashboards/zips/"
            ),
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
