# Generated by Django 6.0.3 on 2026-03-17 16:39

import django.core.validators
import repository.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0015_samplephotos_remove_sample_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutphoto",
            name="image",
            field=models.FileField(
                upload_to="about/photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tif",
                            "tiff",
                            "svg",
                            "ico",
                            "heic",
                            "heif",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="datasets/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tif",
                            "tiff",
                            "svg",
                            "ico",
                            "heic",
                            "heif",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="samplephoto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="samplephoto",
            name="image",
            field=models.FileField(
                upload_to=repository.models._unique_photo_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tif",
                            "tiff",
                            "svg",
                            "ico",
                            "heic",
                            "heif",
                        ]
                    )
                ],
            ),
        ),
    ]
