# Generated by Django 6.0.3 on 2026-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0016_allow_all_image_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Documentation", max_length=200)),
                ("content", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
