from django.urls import path
from . import views

app_name = "repository"

urlpatterns = [
    path("", views.home, name="home"),
    path("datasets/<slug:slug>/", views.dataset_detail, name="detail"),
    path("upload/", views.upload_dataset, name="upload"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
    path("collections/", views.collections_view, name="collections"),
    path("docs/", views.docs_view, name="docs"),
    path("datasets/<slug:slug>/delete/", views.delete_dataset, name="delete"),
    path("datasets/<slug:slug>/edit/", views.edit_dataset, name="edit"),
    path("samples/", views.samples_view, name="samples"),
    path("samples/download/", views.samples_csv_view, name="samples_csv"),
    path("samples/column-values/", views.column_values_view, name="column_values"),
    path("samples/suggest/", views.samples_suggest_view, name="samples_suggest"),
    path("datasets/<slug:slug>/files/add/", views.add_file, name="add_file"),
    path("datasets/<slug:slug>/files/<int:pk>/delete/", views.delete_file, name="delete_file"),
    path("datasets/<slug:slug>/samples/add/", views.add_sample, name="add_sample"),
    path("datasets/<slug:slug>/samples/<int:pk>/delete/", views.delete_sample, name="delete_sample"),
    path("datasets/<slug:slug>/columns/add/", views.add_sample_column, name="add_sample_column"),
    path("datasets/<slug:slug>/columns/<int:col_id>/delete/", views.delete_sample_column, name="delete_sample_column"),
    path("datasets/<slug:slug>/notebooks/add/", views.add_notebook, name="add_notebook"),
    path("datasets/<slug:slug>/notebooks/<int:pk>/delete/", views.delete_notebook, name="delete_notebook"),
    path("datasets/<slug:slug>/notebooks/<int:pk>/rebuild/", views.rebuild_dashboard, name="rebuild_dashboard"),
    path("datasets/<slug:slug>/samples/<int:pk>/edit/", views.edit_sample, name="edit_sample"),
    path("datasets/<slug:slug>/columns/<int:col_id>/rename/", views.rename_sample_column, name="rename_sample_column"),
    path("datasets/<slug:slug>/columns/<int:col_id>/unit/", views.set_column_unit, name="set_column_unit"),
    path("datasets/<slug:slug>/columns/<int:col_id>/group/", views.set_column_group, name="set_column_group"),
    path("datasets/<slug:slug>/samples/upload-csv/", views.upload_csv_samples, name="upload_csv_samples"),
    path("datasets/<slug:slug>/samples/<int:pk>/photo/", views.upload_sample_photo, name="upload_sample_photo"),
    path("datasets/<slug:slug>/samples/<int:sample_pk>/photo/<int:photo_pk>/delete/", views.delete_sample_photo, name="delete_sample_photo"),
    path("datasets/<slug:slug>/access/add/", views.add_dataset_access, name="add_dataset_access"),
    path("datasets/<slug:slug>/access/<int:user_id>/remove/", views.remove_dataset_access, name="remove_dataset_access"),
    path("todo/", views.todo_view, name="todo"),
    path("todo/add/", views.todo_add, name="todo_add"),
    path("todo/<int:pk>/toggle/", views.todo_toggle, name="todo_toggle"),
    path("todo/<int:pk>/edit/", views.todo_edit, name="todo_edit"),
    path("todo/<int:pk>/delete/", views.todo_delete, name="todo_delete"),
    path("todo/clear-done/", views.todo_clear_done, name="todo_clear_done"),
    path("datasets/<slug:slug>/overview-photos/add/", views.upload_dataset_photo, name="upload_dataset_photo"),
    path("datasets/<slug:slug>/overview-photos/<int:photo_pk>/delete/", views.delete_dataset_photo, name="delete_dataset_photo"),
    path("about/", views.about_view, name="about"),
    path("about/photos/<int:pk>/delete/", views.about_photo_delete, name="about_photo_delete"),
]
